logging:
  level: trace
service:
  name: mpic
  port: 8086
  cors: "*"
  max_body_size: 100kb
  secure_cookie: false
listeners:
  action_api_basepath: https://meta.wikimedia.org
database:
  engine: mysql
  host: xlab-db
  username: maria
  database: mpic
  port: 3306

# Part 3 of disabling authentication: If the following Identity Provider (IdP) config isn't
# provided, then xLab will throw an error and exit
idp:
  oidc_url: https://idp-test.wikimedia.org/oidc
  client_id: mpic_next
